function feature_data = import_features(filename, dataLines)
%IMPORTFILE Import data from a text file
%  DOD001TPIHARMONICSTABLE = IMPORTFILE(FILENAME) reads data from text
%  file FILENAME for the default selection.  Returns the data as a table.
%
%  DOD001TPIHARMONICSTABLE = IMPORTFILE(FILE, DATALINES) reads data for
%  the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  DoD001TPIHarmonicsTable = importfile("/Users/nlsschim/Documents/LAB/ML_TBI/june_data/DoD001_TPIHarmonicsTable.csv", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 03-Aug-2020 10:04:33

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 22);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Var1", "Var2", "Var3", "Var4", "Var5", "Var6", "Var7", "h1Real", "h1Imag", "h2Real", "h2Imag", "h3Real", "h3Imag", "h4Real", "h4Imag", "h5Real", "h5Imag", "Var18", "Var19", "Var20", "Var21", "Var22"];
opts.SelectedVariableNames = ["h1Real", "h1Imag", "h2Real", "h2Imag", "h3Real", "h3Imag", "h4Real", "h4Imag", "h5Real", "h5Imag"];
opts.VariableTypes = ["string", "string", "string", "string", "string", "string", "string", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "string", "string", "string", "string", "string"];
opts = setvaropts(opts, [1, 2, 3, 4, 5, 6, 7, 18, 19, 20, 21, 22], "WhitespaceRule", "preserve");
opts = setvaropts(opts, [1, 2, 3, 4, 5, 6, 7, 18, 19, 20, 21, 22], "EmptyFieldRule", "auto");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
feature_data = readtable(filename, opts);

end